export const city = [
    "TOP CITIES",
    "New Delhi",
    "Gurgaon",
    "Pune",
    "Mumbai",
    "Bengaluru",
    "Kolkata",
    "Hyderabad",
    "Ahmedabad",
    "Chennai",
    "Indore",
    "Lucknow",
    "Jaipur",
    "Chandigarh",
    "Bhopal",
    "Noida",
    "Navi Mumbai",
    "Surat",
    "Patna",
    "Ludhiana",
    "Bhubaneshwar",
    "ALL CITIES",
    "Abohar",
    "Adilabad",
    "Adoni",
    "Agar",
    "Agartala",
    "Agra",
    "Ahmednagar",
    "Aizawl",
    "Ajmer",
    "Akola",
    "Alappuzha",
    "Aligarh",
    "Alipurduar",
    "Alirajpur",
    "Allahabad",
    "Almora",
    "Alwar",
    "Ambala",
    "Ambattur",
    "Ambedkar Nagar",
    "Amravati",
    "Amreli",
    "Amritsar",
    "Amroha",
    "Anand",
    "Anantapur",
    "Ananthnag",
    "Anantnag",
    "Angamally",
    "Angul",
    "Ankleshwar",
    "Annur",
    "Anuppur",
    "Arakkonam",
    "Arambag",
    "Arantangi",
    "Araria",
    "Arcot",
    "Ariyalur",
    "Arwal",
    "Asansol",
    "Ashok Nagar",
    "Assaudh",
    "Attuvampatti",
    "Auraiya",
    "Aurangabad Bihar",
    "Aurangabad Maharashtra",
    "Aviyur",
    "Ayyangarkulam",
    "Azamgarh",
    "Badlapur",
    "Bagalkot",
    "Bageshwar",
    "Baghpat",
    "Bagpat",
    "Bahadurgarh",
    "Bahraich",
    "Baksa",
    "Balaghat",
    "Balangir",
    "Baleswar",
    "Ballia",
    "Bally",
    "Balrampur",
    "Banaskantha",
    "Banda",
    "Bangalore",
    "Bangalore Rural",
    "Banka",
    "Bankura",
    "Banswara",
    "Barabanki",
    "Baramati",
    "Baramulla",
    "Baran",
    "Baraut",
    "Bardhaman",
    "Bareilly",
    "Bargarh",
    "Barmer",
    "Barnala",
    "Barpeta",
    "Barrackpore",
    "Baruipur",
    "Barwani",
    "Basirhat",
    "Bastar",
    "Basti",
    "Bathinda",
    "Beawar",
    "Beed",
    "Begumganj",
    "Begusarai",
    "Behraghora",
    "Behrampur",
    "Belgaum",
    "Bellary",
    "Belur",
    "Betul",
    "Betul Ganj",
    "Bhadrak",
    "Bhadravati Karnataka",
    "Bhagalpur",
    "Bhandara",
    "Bharatpur",
    "Bharuch",
    "Bhatkal",
    "Bhavani",
    "Bhavnagar",
    "Bhilai",
    "Bhilwara",
    "Bhind",
    "Bhiwadi",
    "Bhiwandi",
    "Bhiwani",
    "Bhojpur",
    "Bhopal",
    "Bhubaneshwar",
    "Bhuna",
    "Bhusawal",
    "Bidar",
    "Bijapur Chattisgarh",
    "Bijapur Karnataka",
    "Bijnor",
    "Bikaner",
    "Bilaspur Chattisgarh",
    "Bilaspur Himachal Pradesh",
    "Birbhum",
    "Bishnupur",
    "Boisar",
    "Bokaro",
    "Bongaigaon",
    "Bongaon",
    "Botad",
    "Boudh",
    "Budaun",
    "Budgam",
    "Bukkapatnam",
    "Bulandshahr",
    "Buldana",
    "Buldhana",
    "Bundi",
    "Burdwan",
    "Burhanpur",
    "Buxar",
    "Cachar",
    "Calicut",
    "Chamarajanagar",
    "Chamba",
    "Chamoli",
    "Champawat",
    "Champhai",
    "Chandauli",
    "Chandel",
    "Chandigarh",
    "Chandrapur",
    "Changanassery",
    "Changlang",
    "Chatra",
    "Chennai",
    "Chhatarpur",
    "Chhindwara",
    "Chikkaballapur",
    "Chikkaballapura",
    "Chikmagalur",
    "Chintamani",
    "Chitradurga",
    "Chitrakoot",
    "Chittoor",
    "Chittorgarh",
    "Chrompet",
    "Churachandpur",
    "Churu",
    "Cochin",
    "Coimbatore",
    "Cooch Behar",
    "Cuddalore",
    "Cuddapah",
    "Cuttack",
    "Dadra & Nagar Haveli",
    "Dahanu",
    "Dahod",
    "Dakshina Kannada",
    "Daman",
    "Damoh",
    "Dantewada",
    "Darbhanga",
    "Darjiling",
    "Darrang",
    "Datia",
    "Dausa",
    "Davangere",
    "Debagarh",
    "Dehradun",
    "Delhi",
    "Deoghar",
    "Deoria",
    "Dera Bassi",
    "Devanahalli",
    "Dewas",
    "Dhakaoli",
    "Dhalai",
    "Dhamtari",
    "Dhanbad",
    "Dhar",
    "Dharmapuri",
    "Dharwad",
    "Dhemaji",
    "Dhenkanal",
    "Dholpur",
    "Dhone",
    "Dhubri",
    "Dhule",
    "Dhully",
    "Dibang Valley",
    "Dibrugarh",
    "Dibrugarh Tamil Nadu",
    "Dimapur",
    "Dindigul",
    "Dindori",
    "Dispur",
    "Diu",
    "Doda",
    "Dombivli",
    "Dombivli Station",
    "Dumka",
    "Dungarpur",
    "Durg",
    "Durgapur",
    "East Champaran",
    "East Garo Hills",
    "East Godavari",
    "East Kameng",
    "East Khasi Hills",
    "East Midnapore",
    "East Nimar",
    "East Siang",
    "East Sikkim",
    "East Singhbhum",
    "Ellanaickenpatti",
    "Ernakulam",
    "Erode",
    "Etah",
    "Etawah",
    "Faizabad",
    "Faridabad",
    "Faridkot",
    "Farrukhabad",
    "Fatehabad",
    "Fatehgarh Sahib",
    "Fatehpur",
    "Fazilka",
    "Firozabad",
    "Firozpur",
    "Gadag",
    "Gadarwara",
    "Gadchiroli",
    "Gajapati",
    "Gandhinagar",
    "Ganganagar",
    "Gangtok",
    "Ganjam",
    "Garhwa",
    "Gariaband",
    "Gautam Buddha Nagar",
    "Gaya",
    "Ghaziabad",
    "Ghazipur",
    "Gir Somnath",
    "Giridh",
    "Goa",
    "Goalpara",
    "Gobichettipalayam",
    "Godda",
    "Golaghat",
    "Golaniya",
    "Gonda",
    "Gondia",
    "Gopalganj",
    "Gorakhpur",
    "Greater Noida",
    "Greater Thane",
    "Gulbarga",
    "Gumla",
    "Guna",
    "Guntur",
    "Gurdaspur",
    "Gurgaon",
    "Guwahati",
    "Gwalior",
    "Hailakandi",
    "Halol",
    "Hamirpur Himachal Pradesh",
    "Hamirpur Uttar Pradesh",
    "Hansi",
    "Hanumangarh",
    "Hapur",
    "Harapanahalli",
    "Harda",
    "Hardoi",
    "Haridwar",
    "Hassan",
    "Hathras",
    "Haveri",
    "Hazaribag",
    "Hazaribagh",
    "Hinauti",
    "Hindaun",
    "Hingoli",
    "Hisar",
    "Hojai",
    "Hooghly",
    "Hosakote",
    "Hoshangabad",
    "Hoshiarpur",
    "Hoskote",
    "Hospet",
    "Hosur",
    "Howrah",
    "Hubli",
    "Hyderabad",
    "Ichalkaranji",
    "Idukki",
    "Imphal",
    "Imphal East",
    "Imphal West",
    "Indore",
    "Itanagar",
    "Jabalpur",
    "Jagatsinghapur",
    "Jaintia Hills",
    "Jaipur",
    "Jaisalmer",
    "Jajapur",
    "Jalandhar",
    "Jalaun",
    "Jalgaon",
    "Jallipatti",
    "Jalna",
    "Jalore",
    "Jalpaiguri",
    "Jammu",
    "Jamnagar",
    "Jamshedpur",
    "Jamtara",
    "Jamui",
    "Janjgir-Champa",
    "Jashpur",
    "Jaunpur",
    "Jayamala",
    "Jehanabad",
    "Jhabua",
    "Jhajjar",
    "Jhalawar",
    "Jhansi",
    "Jhargram",
    "Jharsuguda",
    "Jhujhunu",
    "Jind",
    "Jodhpur",
    "Jorhat",
    "Junagadh",
    "Jyotiba Phule Nagar",
    "Kachchh",
    "Kadamakkudy",
    "Kadapa",
    "Kadiri",
    "Kadthal",
    "Kaghaz Nagar",
    "Kaimur Bhabua",
    "Kaithal",
    "Kakinada",
    "Kalahandi",
    "Kalipahari",
    "Kallakurichi",
    "Kalligudi",
    "Kalyani",
    "Kamrup",
    "Kanadukathan",
    "Kanchipuram",
    "Kandhamal",
    "Kandukur",
    "Kangra",
    "Kanker",
    "Kannauj",
    "Kannur",
    "Kanpur",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Kansapuram",
    "Kanyakumari",
    "Kapurthala",
    "Karad",
    "Karaikal",
    "Karaikudi",
    "Karatholuvu",
    "Karauli",
    "Karbi Anglong",
    "Kargil",
    "Karimganj",
    "Karimnagar",
    "Karnal",
    "Karupatti",
    "Karur",
    "Karwar",
    "Kasaragod",
    "Kathua",
    "Katihar",
    "Katni",
    "Kattupakkam",
    "Kaushambi",
    "Kavaratti",
    "Kawardha",
    "Kendrapara",
    "Kendujhar",
    "Khagaria",
    "Khammam",
    "Khandwa",
    "Khanna",
    "Kharagpur",
    "Khargone",
    "Kheda",
    "Kheri",
    "Khorda",
    "Kichha",
    "Kinnaur",
    "Kiphire",
    "Kishanganj",
    "Kochi",
    "Kodagu",
    "Kodaikanal Observatory",
    "Koderma",
    "Kohima",
    "Kokrajhar",
    "Kolar",
    "Kolasib",
    "Kolhapur",
    "Kolkata",
    "Kollam",
    "Kooram",
    "Koppal",
    "Koraput",
    "Korba",
    "Koriya",
    "Kota",
    "Kothakudi",
    "Kothur",
    "Kottayam",
    "Kovilpatti",
    "Koyilandy",
    "Kozhikode",
    "Krishna",
    "Krishnagiri",
    "Kulgam",
    "Kullu",
    "Kumbakonam",
    "Kumburvayal",
    "Kundli",
    "Kupwara",
    "Kurnool",
    "Kurukkalpatti",
    "Kurukshetra",
    "Kurung Kumey",
    "Kushinagar",
    "Kutch",
    "Laddivadi",
    "Lahul & Spiti",
    "Lakhimpur",
    "Lakhisarai",
    "Lakshadweep",
    "Lalitpur",
    "Lambakheda",
    "Latehar",
    "Latur",
    "Lawngtlai",
    "Leh",
    "Lohardaga",
    "Lohit",
    "Lonavala",
    "Longleng",
    "Lower Dibang Valley",
    "Lower Subansiri",
    "Lucknow",
    "Ludhiana",
    "Lunglei",
    "Machur",
    "Madhepura",
    "Madhubani",
    "Madhupur",
    "Madikeri",
    "Madurai",
    "Mahabubabad",
    "Mahabubnagar",
    "Mahadanapuram",
    "Maharajganj",
    "Mahasamund",
    "Mahbub Nagar",
    "Mahe",
    "Mahendragarh",
    "Mahoba",
    "Mainaguri",
    "Mainpuri",
    "Majuli",
    "Malappuram",
    "Malda",
    "Malkangiri",
    "Malout",
    "Mammit",
    "Manakudi",
    "Manapparai",
    "Manawar",
    "Mandi",
    "Mandi Gobindgarh",
    "Mandla",
    "Mandsaur",
    "Mandya",
    "Mangalore",
    "Manipal",
    "Mannargudi",
    "Mansa",
    "Margao",
    "Marigaon",
    "Mathura",
    "Mau",
    "Mayurbhanj",
    "Medak",
    "Meenkashipuram",
    "Meerut",
    "Mehsana",
    "Melaparuthigudi",
    "Melpallam",
    "Melpattamkarisalkulam",
    "Melvisharam",
    "Midnapore",
    "Mirzapur",
    "Moga",
    "Mohali",
    "Mohanur",
    "Mokokchung",
    "Mon",
    "Moradabad",
    "Morena",
    "Muchipara",
    "Mughal Sarai",
    "Muktsar",
    "Mumbai",
    "Mumbai Extension",
    "Munger",
    "Murshidabad",
    "Muzaffarnagar",
    "Muzaffarpur",
    "Mysore",
    "Nabarangapur",
    "Nadia",
    "Nadiad",
    "Naduvakurichi",
    "Nagaon",
    "Nagapattinam",
    "Nagaur",
    "Nagpur",
    "Naidupuram",
    "Nainital",
    "Najibabad",
    "Nalanda",
    "Nalbari",
    "Nalgonda",
    "Namakkal",
    "Nanded",
    "Nandurbar",
    "Narayanpur",
    "Narmada",
    "Narnaul",
    "Narsinghpur",
    "Narsipatnam",
    "Nashik",
    "Navi Mumbai",
    "Navsari",
    "Nawada",
    "Nawanshahr",
    "Naxalbari",
    "Nayagarh",
    "Neemrana",
    "Neemuch",
    "Nelamangala",
    "Nellore",
    "Nerur",
    "New Delhi",
    "Nicobar",
    "Nilgiri",
    "Nilgiris",
    "Nizamabad",
    "Noida",
    "North 24 Paragnas",
    "North 24 Parganas",
    "North And Middle Andaman",
    "North Cachar Hills",
    "North Dinajpur",
    "North Goa",
    "North Sikkim",
    "North Tripura",
    "Nowda",
    "Nuapada",
    "Nuh",
    "Nuvem",
    "Ooty",
    "Osmanabad",
    "Pakur",
    "Palakkad",
    "Palamalai",
    "Palamu",
    "Palani",
    "Palghar",
    "Pali",
    "Pambakovil Shandy",
    "Panaji",
    "Panchkula",
    "Panchmahal",
    "Panipat",
    "Panna",
    "Panvel - Station",
    "Papanasam",
    "Pappankulam",
    "Pappinaickenpatti",
    "Papum Pare",
    "Paradip",
    "Parbhani",
    "Pasumpon",
    "Patan",
    "Pathanamthitta",
    "Pathankot",
    "Patiala",
    "Patna",
    "Pauri Garhwal",
    "Pavitram",
    "Perambalur",
    "Peren",
    "Phalghat",
    "Phek",
    "Pilani",
    "Pilibhit",
    "Pinnathur",
    "Pithoragarh",
    "Pondicherry",
    "Ponga",
    "Poonamalle",
    "Porbandar",
    "Port Blair",
    "Prakasam",
    "Pratapgarh",
    "Proddatur",
    "Pudukkottai",
    "Pulankurichi",
    "Pulavadi",
    "Puludipatti",
    "Pulwama",
    "Pune",
    "Pungamuthur",
    "Purba Bardhaman",
    "Purbasthali",
    "Puri",
    "Purnia",
    "Puruliya",
    "Puzhal",
    "Quilon",
    "Raebareli",
    "Raichur",
    "Raigad Maharashtra",
    "Raigarh Chattisgarh",
    "Raikasba",
    "Raipur",
    "Raisen",
    "Rajahmundry",
    "Rajauri",
    "Rajgangpur",
    "Rajgarh",
    "Rajkot",
    "Rajnandgaon",
    "Rajpura",
    "Rajsamand",
    "Ramanagar",
    "Ramanathapuram",
    "Ramgarh",
    "Rampur",
    "Ranchi",
    "Rangareddi",
    "Rangareddy",
    "Ranipet",
    "Ratlam",
    "Ratnagiri",
    "Raurkela",
    "Rayagada",
    "Reasi",
    "Rewa",
    "Rewari",
    "Ri Bhoi",
    "Rishikesh",
    "Rohtak",
    "Rohtas",
    "Roorkee",
    "Ropar",
    "Rourkela",
    "Rudraprayag",
    "Rudrapur",
    "Rupnagar",
    "Rurka Kalan",
    "S.A.S. Nagar",
    "Sabarkantha",
    "Sagar",
    "Saharanpur",
    "Saharsa",
    "Sahibganj",
    "Saiha",
    "Salem",
    "Samastipur",
    "Sambalpur",
    "Sambhal",
    "Sangareddy",
    "Sangli",
    "Sangrur",
    "Sant Kabir Nagar",
    "Sant Ravidas Nagar",
    "Saran",
    "Satara",
    "Satna",
    "Sawai Madhopur",
    "Secunderabad",
    "Sehore",
    "Senapati",
    "Seoni",
    "Seraikela-Kharsawan",
    "Serchhip",
    "Shahapur",
    "Shaharanpur",
    "Shahdol",
    "Shahjahanpur",
    "Shahpura",
    "Shajapur",
    "Shamshabad",
    "Sheikhpura",
    "Sheohar",
    "Sheopur",
    "Shikohabad",
    "Shillong",
    "Shimla",
    "Shimoga",
    "Shivpuri",
    "Shrawasti",
    "Shyamnagar",
    "Sibmandir",
    "Sibsagar",
    "Siddharthnagar",
    "Sidhi",
    "Sihora",
    "Siliguri",
    "Silvassa",
    "Simdega",
    "Simga",
    "Sindhudurg",
    "Singrauli",
    "Sirkaali",
    "Sirmaur",
    "Sirohi",
    "Sirsa",
    "Sitamarhi",
    "Sitapur",
    "Sivaganga",
    "Sivakasi",
    "Sivasagar",
    "Siwan",
    "Solan",
    "Solapur",
    "Sonapur",
    "Sonarpur",
    "Sonbhadra",
    "Sonipat",
    "Sonitpur",
    "Soro",
    "South 24 Parganas",
    "South Andaman",
    "South Dinajpur",
    "South Garo Hills",
    "South Goa",
    "South Sikkim",
    "South Tripura",
    "Sricity",
    "Srikakulam",
    "Srinagar",
    "Subarnapur",
    "Sujangarh",
    "Sultanpur",
    "Sundergarh",
    "Supaul",
    "Surat",
    "Surendranagar",
    "Surguja",
    "T Pudupatti",
    "Tadipatri",
    "Talasari",
    "Tamenglong",
    "Tapi",
    "Tarn Taran",
    "Tawang",
    "Tehri Garhwal",
    "Tenkasi",
    "Thane",
    "Thanjavur",
    "The Dangs",
    "Theni",
    "Thimmarajanpettai",
    "Thirukkalukundram",
    "Thirukkannamangaikottam",
    "Thiruvaiyaru",
    "Thiruvarur",
    "Thoothukudi",
    "Thoubal",
    "Thrissur",
    "Thungavi",
    "Tikamgarh",
    "Timarni",
    "Tinsukia",
    "Tirap",
    "Tiruchendur",
    "Tiruchirappalli",
    "Tiruklalikundram",
    "Tirumani",
    "Tirunelveli",
    "Tirupati",
    "Tiruppur",
    "Tirupur",
    "Tirur",
    "Tiruttani",
    "Tiruvalla",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Titilagarh",
    "Tohana",
    "Tonk",
    "Trimulgherry",
    "Trivandrum",
    "Tuensang",
    "Tumkur",
    "Turaiyur Koitpatti",
    "Tuticorin",
    "Udaipur Rajasthan",
    "Udaipur Tripura",
    "Udayarpalayam",
    "Udham Singh Nagar",
    "Udhampur",
    "Udupi",
    "Ujjain",
    "Ukhrul",
    "Umaria",
    "Una",
    "Unnao",
    "Upper Siang",
    "Upper Subansiri",
    "Uttara Kannada",
    "Uttarkashi",
    "Vadagarai",
    "Vadakara",
    "Vadodara",
    "Vaishali",
    "Valsad",
    "Vandavasi",
    "Vapi",
    "Varanasi",
    "Vattur",
    "Vellore",
    "Vidisha",
    "Vijayawada",
    "Vikarabad",
    "Villupuram",
    "Virudhunagar",
    "Visakhapatnam",
    "Visalakshi Nagar",
    "Vizianagaram",
    "Warangal",
    "Wardha",
    "Washim",
    "Wayanad",
    "West Champaran",
    "West Garo Hills",
    "West Godavari",
    "West Kameng",
    "West Khasi Hills",
    "West Midnapore",
    "West Nimar",
    "West Siang",
    "West Sikkim",
    "West Singhbhum",
    "West Tripura",
    "Wokha",
    "Y.S.R.",
    "Yadgir",
    "Yamunanagar",
    "Yavatmal",
    "Zunhebotto"
];

